name: Publish New Version

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Build Asciidoctor
        run: ./gradlew asciidoctor
      - name: Deploy
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: ./build/docs/asciidoc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
